spring:
  cloud:
    gateway:
      routes:
        - id: admin_route
          uri: lb://renren-fast
          ## 将http://localhost:88/api/captcha.jpg 转换为 http://localhost:8080/renren-fast/captcha.jpg
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
